import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { colors } from '../theme/colors';
import {
  ActivityIndicator,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from 'react-native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { RouteProp, useNavigation, useRoute } from '@react-navigation/native';
import { DataTable, TableText } from '../components/DataTable';
import { ExamAttendanceModal } from '../components/ExamAttendanceModal';
import { ExamSessionPicker } from '../components/ExamSessionPicker';
import { ScopeFilterPanel } from '../components/ScopeFilterPanel';
import {
  buildLevelFilterOptions,
  buildRegionFilterOptions,
  buildSchoolFilterOptions,
} from '../utils/filterOptions';
import {
  canGenerateStudentList,
  resolveScopeFiltersAsync,
} from '../utils/scopeDefaults';
import { StudentPhotoModal } from '../components/StudentPhotoModal';
import { TableActionButton } from '../components/TableActionButton';
import { useAuth } from '../context/AuthContext';
import { getExamAttendanceMap, todayDateString } from '../services/examAttendanceService';
import { getRegions } from '../services/regionService';
import { getSchoolLevels } from '../services/schoolService';
import { loadAccessibleSchools } from '../services/accessibleSchools';
import { getStudents } from '../services/studentService';
import { ExamAttendanceRecord, Region, School, Student } from '../types';
import { StudentsStackParamList } from '../navigation/types';

type Nav = NativeStackNavigationProp<StudentsStackParamList, 'StudentBrowse'>;
type Route = RouteProp<StudentsStackParamList, 'StudentBrowse'>;

export function StudentBrowseScreen() {
  const navigation = useNavigation<Nav>();
  const route = useRoute<Route>();
  const { user } = useAuth();
  const routeParams = route.params;

  const [regions, setRegions] = useState<Region[]>([]);
  const [levels, setLevels] = useState<string[]>([]);
  const [schools, setSchools] = useState<School[]>([]);
  const [students, setStudents] = useState<Student[]>([]);
  const [selectedRegionId, setSelectedRegionId] = useState<number | null>(null);
  const [selectedRegion, setSelectedRegion] = useState<string | null>(null);
  const [selectedLevel, setSelectedLevel] = useState<string | null>(null);
  const [selectedSchoolId, setSelectedSchoolId] = useState<number | null>(null);
  const [examSubject, setExamSubject] = useState('');
  const [examDate, setExamDate] = useState(todayDateString());
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [totalCount, setTotalCount] = useState(0);
  const [loadingFilters, setLoadingFilters] = useState(true);
  const [loadingSchoolOptions, setLoadingSchoolOptions] = useState(false);
  const [loadingStudents, setLoadingStudents] = useState(false);
  const [loadingMore, setLoadingMore] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [listGenerated, setListGenerated] = useState(false);
  const [attendanceMap, setAttendanceMap] = useState<Map<string, ExamAttendanceRecord>>(new Map());
  const [photoStudentNo, setPhotoStudentNo] = useState<string | null>(null);
  const [attendanceStudent, setAttendanceStudent] = useState<Student | null>(null);
  const [scopeLabel, setScopeLabel] = useState<string | null>(null);
  const [lockedFilters, setLockedFilters] = useState<{
    region?: boolean;
    level?: boolean;
    school?: boolean;
  }>({});
  const autoGenerateDone = useRef(false);

  const refreshAttendance = useCallback(
    async (studentList?: Student[]) => {
      const subject = examSubject.trim();
      const date = examDate.trim();
      const list = studentList ?? students;
      if (!subject || !date || list.length === 0) {
        setAttendanceMap(new Map());
        return;
      }
      const map = await getExamAttendanceMap(
        subject,
        date,
        list.map((s) => s.studentNo)
      );
      setAttendanceMap(map);
    },
    [examDate, examSubject, students]
  );

  const getAttendanceLabel = (student: Student) => {
    const subject = examSubject.trim();
    if (!subject) return '—';
    const date = examDate.trim();
    const datedKey = `${student.studentNo}::${subject.toLowerCase()}::${date}`;
    const plainKey = `${student.studentNo}::${subject.toLowerCase()}`;
    const record = attendanceMap.get(datedKey) || attendanceMap.get(plainKey);
    return record?.status || '—';
  };

  const regionOptions = useMemo(() => {
    const scoped = buildRegionFilterOptions(regions);
    if (lockedFilters.region && selectedRegion) {
      return scoped.filter((o) => o.value === selectedRegion);
    }
    return scoped;
  }, [lockedFilters.region, regions, selectedRegion]);

  const levelOptions = useMemo(() => {
    const fromSchools = Array.from(
      new Set(schools.map((s) => (s.schoolLevel || '').trim() || 'Unspecified'))
    ).sort();
    const source = fromSchools.length ? fromSchools : levels;
    return buildLevelFilterOptions(source);
  }, [levels, schools]);
  const schoolOptions = useMemo(() => buildSchoolFilterOptions(schools), [schools]);

  const schoolScopeMode = user?.accessScope?.scopeType === 'school';
  const canGenerate = canGenerateStudentList(user, selectedRegion, selectedRegionId, selectedSchoolId);

  useEffect(() => {
    (async () => {
      try {
        const [regionRows, levelRows] = await Promise.all([getRegions(), getSchoolLevels()]);
        setRegions(regionRows);
        setLevels(levelRows);

        const resolved = await resolveScopeFiltersAsync(user, regionRows);
        setScopeLabel(resolved.scopeLabel);
        setLockedFilters({
          region: resolved.lockRegion,
          level: resolved.lockLevel,
          school: resolved.lockSchool,
        });

        setSelectedRegionId(
          routeParams?.regionId ?? resolved.regionId ?? null
        );
        setSelectedRegion(routeParams?.region ?? resolved.regionName);
        setSelectedLevel(routeParams?.level ?? resolved.level);
        setSelectedSchoolId(routeParams?.schoolId ?? resolved.schoolId);
      } catch {
        setError('Failed to load regions and levels');
      } finally {
        setLoadingFilters(false);
      }
    })();
  }, [routeParams?.level, routeParams?.region, routeParams?.schoolId, user]);

  const loadSchoolOptions = useCallback(async () => {
    if (loadingFilters) return;

    const needsRegion =
      !schoolScopeMode &&
      !selectedRegionId &&
      !selectedRegion &&
      !selectedSchoolId &&
      !user?.accessScope?.scopeType;

    if (needsRegion) {
      setSchools([]);
      if (!lockedFilters.school) setSelectedSchoolId(null);
      return;
    }

    setLoadingSchoolOptions(true);
    try {
      const rows = await loadAccessibleSchools(user, {
        regionId: schoolScopeMode ? null : selectedRegionId,
        region: schoolScopeMode ? null : selectedRegion,
        level: selectedLevel,
      });
      setSchools(rows);
      if (selectedSchoolId && !rows.some((s) => s.schoolId === selectedSchoolId)) {
        if (!lockedFilters.school) setSelectedSchoolId(null);
      }
    } catch {
      setError('Failed to load school filter options');
      setSchools([]);
    } finally {
      setLoadingSchoolOptions(false);
    }
  }, [
    loadingFilters,
    lockedFilters.school,
    schoolScopeMode,
    selectedLevel,
    selectedRegion,
    selectedRegionId,
    selectedSchoolId,
    user,
  ]);

  useEffect(() => {
    loadSchoolOptions();
    setListGenerated(false);
    setStudents([]);
  }, [loadSchoolOptions, loadingFilters, selectedRegion, selectedRegionId, selectedLevel]);

  const generateList = useCallback(
    async (pageNum = 1, append = false) => {
      if (!canGenerateStudentList(user, selectedRegion, selectedRegionId, selectedSchoolId)) {
        setError('Select a region or school within your access scope');
        return;
      }
      if (pageNum === 1) setLoadingStudents(true);
      else setLoadingMore(true);
      setError(null);
      try {
        const result = await getStudents({
          page: pageNum,
          pageSize: 50,
          regionId: schoolScopeMode ? undefined : selectedRegionId ?? undefined,
          region: schoolScopeMode
            ? undefined
            : !selectedRegionId
              ? selectedRegion || undefined
              : undefined,
          level: selectedLevel || undefined,
          schoolId: selectedSchoolId || undefined,
        });
        let loaded: Student[] = result.items;
        setStudents((prev) => {
          loaded = append ? [...prev, ...result.items] : result.items;
          return loaded;
        });
        setPage(result.page);
        setTotalPages(result.totalPages);
        setTotalCount(result.totalCount);
        setListGenerated(true);
        await refreshAttendance(loaded);
      } catch {
        setError('Failed to generate student list');
      } finally {
        setLoadingStudents(false);
        setLoadingMore(false);
      }
    },
    [refreshAttendance, schoolScopeMode, selectedLevel, selectedRegion, selectedRegionId, selectedSchoolId, user]
  );

  useEffect(() => {
    if (loadingFilters || autoGenerateDone.current) return;
    const shouldAuto =
      routeParams?.autoGenerate ||
      user?.accessScope?.scopeType === 'school' ||
      Boolean(routeParams?.schoolId);
    if (shouldAuto && canGenerate) {
      autoGenerateDone.current = true;
      generateList(1, false);
    }
  }, [
    canGenerate,
    generateList,
    loadingFilters,
    routeParams?.autoGenerate,
    routeParams?.schoolId,
    user?.accessScope?.scopeType,
  ]);

  useEffect(() => {
    if (listGenerated && students.length > 0 && examSubject.trim() && examDate.trim()) {
      refreshAttendance(students);
    }
  }, [examDate, examSubject, listGenerated, refreshAttendance, students]);

  const studentColumns = useMemo(
    () => [
      {
        key: 'row',
        title: 'Row',
        width: 48,
        align: 'center' as const,
        render: (_: Student, rowIndex: number) => <TableText center>{rowIndex + 1}</TableText>,
      },
      {
        key: 'studentNo',
        title: 'Student No',
        width: 100,
        render: (item: Student) => <TableText>{item.registrationNo || item.studentNo}</TableText>,
      },
      {
        key: 'name',
        title: 'Student Name',
        width: 160,
        render: (item: Student) => (
          <Pressable onPress={() => navigation.navigate('StudentDetail', { studentNo: item.studentNo })}>
            <TableText bold>{item.fullName || '—'}</TableText>
          </Pressable>
        ),
      },
      {
        key: 'sex',
        title: 'Sex',
        width: 56,
        align: 'center' as const,
        render: (item: Student) => <TableText center>{item.sex || '—'}</TableText>,
      },
      {
        key: 'examCenter',
        title: 'Exam center',
        width: 140,
        render: (item: Student) => (
          <TableText muted>{item.examCenterName?.trim() || '—'}</TableText>
        ),
      },
      {
        key: 'examStatus',
        title: 'Exam Status',
        width: 96,
        align: 'center' as const,
        render: (item: Student) => {
          const label = getAttendanceLabel(item);
          return (
            <TableText center bold={label !== '—'}>
              {label}
            </TableText>
          );
        },
      },
      {
        key: 'actions',
        title: 'Actions',
        width: 130,
        render: (item: Student) => (
          <View style={styles.actionsCell}>
            <TableActionButton
              label="Photo"
              variant="secondary"
              onPress={() => setPhotoStudentNo(item.studentNo)}
              disabled={!item.hasPicture}
            />
            <TableActionButton
              label="Exam"
              variant="success"
              onPress={() => setAttendanceStudent(item)}
            />
          </View>
        ),
      },
    ],
    [attendanceMap, examDate, examSubject, navigation]
  );

  if (loadingFilters) {
    return (
      <View style={styles.center}>
        <ActivityIndicator size="large" color={colors.primary} />
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <ScrollView contentContainerStyle={styles.scrollContent}>
        <ScopeFilterPanel
          regionOptions={regionOptions}
          levelOptions={levelOptions}
          schoolOptions={schoolOptions}
          selectedRegion={selectedRegion}
          selectedLevel={selectedLevel}
          selectedSchoolId={selectedSchoolId}
          onRegionChange={(v) => {
            setSelectedRegion(v);
            if (v) {
              const match = regions.find((r) => r.name === v);
              setSelectedRegionId(match ? Number(match.auto) : null);
            } else {
              setSelectedRegionId(null);
            }
            if (!lockedFilters.school) setSelectedSchoolId(null);
            setListGenerated(false);
          }}
          onLevelChange={(v) => {
            setSelectedLevel(v);
            setListGenerated(false);
          }}
          onSchoolChange={(v) => {
            setSelectedSchoolId(v);
            setListGenerated(false);
          }}
          lockedFilters={lockedFilters}
          loadingSchools={loadingSchoolOptions}
          schoolScopeMode={schoolScopeMode}
          scopeBanner={
            scopeLabel
              ? `Your access: ${scopeLabel}. Only schools and students in this scope are shown.`
              : null
          }
        />

        <View style={styles.examSubjectBox}>
          <Text style={styles.examSubjectLabel}>Exam date (YYYY-MM-DD)</Text>
          <TextInput
            style={styles.examSubjectInput}
            value={examDate}
            onChangeText={(v) => {
              setExamDate(v);
              setExamSubject('');
            }}
          />
        </View>

        <ExamSessionPicker
          schoolLevel={selectedLevel}
          examDate={examDate}
          selectedSubject={examSubject}
          onSelect={setExamSubject}
        />

        <Pressable
          style={[styles.generateBtn, !canGenerate && styles.generateBtnDisabled]}
          disabled={!canGenerate || loadingStudents}
          onPress={() => generateList(1, false)}
        >
          <Text style={styles.generateBtnText}>
            {loadingStudents ? 'Generating...' : 'Generate student list'}
          </Text>
        </Pressable>

        {error ? <Text style={styles.error}>{error}</Text> : null}

        {listGenerated && !loadingStudents ? (
          <DataTable
            title="Students"
            subtitle={`${totalCount.toLocaleString()} student${totalCount === 1 ? '' : 's'} · showing ${students.length}`}
            columns={studentColumns}
            data={students}
            keyExtractor={(item) => item.studentNo}
            emptyMessage="No students in your access scope"
          />
        ) : null}

        {loadingStudents ? <ActivityIndicator style={{ marginVertical: 24 }} color={colors.primary} /> : null}

        {listGenerated && page < totalPages ? (
          <Pressable
            style={styles.loadMoreBtn}
            disabled={loadingMore}
            onPress={() => generateList(page + 1, true)}
          >
            <Text style={styles.loadMoreText}>
              {loadingMore ? 'Loading...' : `Load more (${students.length} of ${totalCount})`}
            </Text>
          </Pressable>
        ) : null}
      </ScrollView>

      <StudentPhotoModal
        visible={photoStudentNo != null}
        studentNo={photoStudentNo}
        onClose={() => setPhotoStudentNo(null)}
      />

      <ExamAttendanceModal
        visible={attendanceStudent != null}
        student={attendanceStudent}
        defaultSubject={examSubject}
        schoolLevel={selectedLevel || attendanceStudent?.schoolLevel || null}
        examDate={examDate}
        onClose={() => setAttendanceStudent(null)}
        onSaved={() => refreshAttendance(students)}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  scrollContent: { paddingBottom: 24 },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  examSubjectBox: {
    marginHorizontal: 12,
    marginBottom: 10,
    backgroundColor: colors.surface,
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  examSubjectLabel: { fontSize: 12, fontWeight: '600', color: '#444', marginBottom: 6 },
  examSubjectInput: {
    backgroundColor: '#f8faff',
    borderWidth: 1,
    borderColor: '#dde3ee',
    borderRadius: 8,
    padding: 10,
    fontSize: 14,
  },
  generateBtn: {
    backgroundColor: colors.primary,
    marginHorizontal: 12,
    marginBottom: 12,
    padding: 14,
    borderRadius: 10,
    alignItems: 'center',
  },
  generateBtnDisabled: { opacity: 0.5 },
  generateBtnText: { color: colors.white, fontWeight: '600' },
  loadMoreBtn: {
    marginHorizontal: 12,
    marginTop: 4,
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.primary,
    alignItems: 'center',
    backgroundColor: colors.surface,
  },
  loadMoreText: { color: colors.primary, fontWeight: '600' },
  actionsCell: { flexDirection: 'column', alignItems: 'stretch' },
  error: { color: colors.error, textAlign: 'center', margin: 8 },
});